### ISSUE TITLE
Unclear "What should I do?"

### ISSUE THREAD

**Issue by Marco4223** [mattgruter/unfoldedcircle-ircodes#1]
Hi, 
can we have a little bit more instruction docutmentation about how we can/should record/export/formating?
If you have no idea or no time please drop me a meesage an I can try to produce some content.
Cheers
Marco

**Comment by mattgruter** [comment]
Hi Marco

I've added instructions on how to create and export a codeset CSV file.
I'd be happy to merge your suggestions on formatting, I haven't given it much thought so far to be honest as I just download the CSV directly from the remote's web configurator.

/matthias

**Comment by Marco4223** [comment]
Hi Matthias and a happy new year,
the big problem is for the enduser that they need to know how to import and how to share rhere IR codes. 
Whe I'm exporting my settings I can only export ALL IR  commands like this: 
![grafik](https://github.com/mattgruter/unfoldedcircle-ircodes/assets/10371265/6512bebe-8ed4-40de-8ef3-0925d1af5b4b)
But this format Im not able to import or share. 
To do so I have to create a "Infrared" under "Remotes" as and can then (If a new user find it direct) do a bulk import. 
![grafik](https://github.com/mattgruter/unfoldedcircle-ircodes/assets/10371265/772b199c-64b3-42d6-84b1-6eb0603ef390)
If I click the link to get more details for that I get this: 
![grafik](https://github.com/mattgruter/unfoldedcircle-ircodes/assets/10371265/483289e0-372f-4a5c-aade-60850648fe4d)
A little long way for a new user. 
An idea could be:
Having an export button on the IR Filed under Remotes like:
![grafik](https://github.com/mattgruter/unfoldedcircle-ircodes/assets/10371265/0337e490-39d5-4368-b58c-ca458d28b21b)
and an import button on the create page like:
![grafik](https://github.com/mattgruter/unfoldedcircle-ircodes/assets/10371265/fdb72bbb-8d22-43e3-83b4-ad420e1c0f6f)

with an default format like 
![grafik](https://github.com/mattgruter/unfoldedcircle-ircodes/assets/10371265/c3d056a8-1d55-487a-8f84-943484d595e4)


I know that the options with "Delimiter" and "Comments" are more flexible but that can confuse the 0 8 15 User.
Please let me know how U think about this idea. :)
Cheers
MarcO

**Comment by mattgruter** [comment]
Happy new year to you too :-)

I agree that the process of exporting and importing IR codes is far from user friendly. I hope that the Unfoldedcircle team (I'm just a user like yourself) will implement a simpler workflow similar to what you propose in the future. Ideally, users could import IR codes directly from a community "marketplace" of codesets and don't have to download CSV files and then import them through a confusing dialog. I've created this repo as a stop-gap until the remote hopefully supports something natively. I hope that the newly added documentation in this repo's README contributed by David Claeys make it a bit clearer how importing works for everyone.

I'd suggest that we close this issue here and that you open a feature request in their https://github.com/unfoldedcircle/feature-and-bug-tracker repo.

Cheers,
Matthias

**Comment by Marco4223** [comment]
Agree. Did saw that this is the wrong repo for that bug.
